### ISSUE TITLE
what kind of Graphic card should I use to run this code?

### ISSUE THREAD

**Issue by wei1224hf** [martius-lab/wasabi#1]
RTX 4090 , can run this code ?
what's the limit graphic memory should I prepare to run this code?

**Comment by breadli428** [comment]
Hi,

Thanks a lot for the question. To be able to run Isaac Gym, you would need an NVIDIA graphics card. So RTX 4090 would be definitely enough for it. The memory demand is approximately 10G for this project. 

Hope this helps!

Best
